### ISSUE TITLE
The two libs can't be found in the project.

### ISSUE THREAD

**Issue by skyfallsss** [Richarizardd/Self-Supervised-ViT-Path#4]
from pl_bolts.models.self_supervised import resnets
from pl_bolts.utils.semi_supervised import Identity
The two libs can't be found in the project.

**Comment by Richarizardd** [comment]
You can find these libraries in the PyTorch-Lightning extension: https://pytorch-lightning.readthedocs.io/en/latest/ecosystem/bolts.html
