### ISSUE TITLE
Training data

### ISSUE THREAD

**Issue by FoilHao** [Richarizardd/Self-Supervised-ViT-Path#6]
Thanks for your great work!
In the paper, you said you used 1038 TCGA-BRCA for training. The project TCGA-BRCA provides 1062 Diagnostic Slides and 1093 Tissue Slides, and I wonder which type you used.

**Comment by Arkkienkeli** [comment]
I tried to use filters to create special cohort and played around with filters, still could not get 1038, I get 1036 (see an image, 1007 relates to number of cases, not number of WSIs, added 2nd screenshot to clarify). 
Is it possible to share the manifest for gdc-client or other type of list\filters? Thank you! 
![image](https://github.com/Richarizardd/Self-Supervised-ViT-Path/assets/3052376/4cbcba87-7fff-4cea-a6e8-5152fc81f240)

![image](https://github.com/Richarizardd/Self-Supervised-ViT-Path/assets/3052376/80914f97-3b22-44d0-afbb-f3bb65a7a67c)
